### ISSUE TITLE
GitInfo controller does not consider `index=true` frontmatter property

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/docforge#191]
**What happened**:
When there is an `index=true` property in a node, then the node content will be fetched into a /content/.../_index.md file.
However the GitInfo controller is not aware of such an property and it will download the node metadata under /data/.../realName.md.json

**What you expected to happen**:
In the above case, the GitInfo controller should download the file metadata into  /content/.../_index.md file

**How to reproduce it (as minimally and precisely as possible)**:
```
structure:
- name: architecture
  nodes:
  - source: https://github.com/gardener/gardener/blob/master/docs/concepts/architecture.md
    properties:
      index: true
      frontmatter:
        title: Architecture
        remote: https://github.com/gardener/gardener/blob/master/docs/concepts/architecture.md
        weight: 10
```

**Anything else we need to know**:

**How to categorize this issue?**

/kind bug
/priority normal
