### ISSUE TITLE
When nodesSelector and sources exist in a node structure, docforge skips the sources

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/docforge#256]
**What happened**:
Currently it is not possible to define nodesSelector and sources(single nodes) in a node structure. In this scenario, the docforge will completely skip the sources and will process only the nodesSelector. 

The only workaround is if both types are defined under a `structure` section which means to be created a new manifest file and to be added there as a top level nodes

**What you expected to happen**:
The scenario described above should work not only for the structures but for nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Define nodesSelector and a source under the same node.
```
    - name: parent
      nodes:
      - nodesSelector:
          path: <link-to-dir>
      - name: chield-source
        source: <link-to-single-md>
```

**How to categorize this issue?**

/kind bug
/priority 3
