### ISSUE TITLE
Adapt e2e test to not clone website-generator

### ISSUE THREAD

**Issue by Kostov6** [gardener/docforge#389]
**What would you like to be added**:
Temporary we disabled e2e
https://github.com/gardener/docforge/pull/386
Previous to that e2e cloned website-generator and ran `.ci/build`. This creates a dependency to it. Lets instead:
In `.ci/e2e`:
``` bash
...
GITHUB_OAUTH_TOKEN=$(getGitHubToken github_com) tests/e2e/diff.sh
```
And `tests/e2e/diff.sh` should be runnable locally. In `tests/e2e/diff.sh`:
1. build docforge binary. Example: https://github.com/gardener/docforge/blob/ac299ebdfd224a07d1cf4779f1f4093bc36fedfe/.ci/e2e#L51-L52
2. run docforge with a config like this:
``` yaml
manifest: https://github.com/gardener/documentation/blob/master/.docforge/hugo.yaml
destination: hugo
hugo: true
hugo-structural-dirs:
- content
- static
content-files-formats:
- ".md"
- ".html"
- ".js"
- ".scss"
- ".css"
- ".toml"
- ".json"
- ".png"
- ".svg"
resources-download-path: content/__resources
github-oauth-env-map:
  "github.com": GITHUB_OAUTH_TOKEN
skip-link-validation: true
```
3. Check difference between bundle build from master and current docforge

**Why is this needed / describe a real-world scenario**:
e2e has no dependency on website-generator

**How to categorize this?**:

/kind enhancement
/priority 1
