### ISSUE TITLE
Support variables substitution

### ISSUE THREAD

**Issue by g-pavlov** [gardener/docforge#46]
**What would you like to be added**:
Optional definition of variables in a documentations structure manifest.

**Why is this needed**:
Variables can be used to parametrize a structure, encapsulating changes only within a single variables block in the manifest. That: 
- reduces redundancies and thus error-proneness and potentially the length of the manifest
- improves the automation opportunities for employing docforge

Concerning the latter point, a reference case could be the following. 

Consider a documentation structure manifest in the Gardener documentation designed for the Gardener website. The documentation repo is piped in the cicd to release a build upon a release by the Gardener component. With component versions *parameterized* for each link to a component documentation material in the manifest, the documentation release job build can consult with Gardener's component descriptor and its dependencies versions for the new release and automatically update the component versions variables in the manifest. That will ensure automated consistency between the Gardener BoM and the documentation structure BoM encoded in the manifest.

Even without fully automating the release process it is significantly easier to maintain variables values instead of the version in each link in a large document structure.
Example reference structure with variables:
```
var:
- gardener-version: v1.12.0
- gardener-extension-provider-aws-version: v1.15.3
- gardener-github-org-path: https://github.com/gardener
root:
  name: doc
  nodes:
  - name: gardenlet
    contentSelectors:
      - source: ${gardener-github-org-path}/gardener/blob/${gardener-version}/docs/concepts/gardenlet.md
  - name: aws-provider
    contentSelectors:
      - source: ${gardener-github-org-path}/gardener-extension-provider-aws/blob/${gardener-extension-provider-aws-version}/docs/usage-as-operator.md
localityDomain:
  ${gardener-github-org-path}/gardener:
    version: ${gardener-version}
    path: gardener/gardener
  ${gardener-github-org-path}/gardener-extension-provider-aws:
    version: ${gardener-extension-provider-aws-version}
    path: gardener/gardener-extension-provider-aws
```
